### ISSUE TITLE
Display Color Text values instead of Hex values

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [RallyCommunity/CustomChart#39]
When using Display Color in the chart is shows the Hex value and not the "in-system" description name, e.g., pink.

This is not very user friendly for Non-Hex'ers*

*Non-Hex'ers being us that doesn't see colors as hexa-dicimal numbers :-)

**Comment by krmorse** [comment]
This is good feedback.  I can't read hex either.  Can you post a screenshot of your chart configuration so I can understand exactly what you're trying to visualize?  Thanks!

**Comment by shapeles** [comment]
Sure.

Our customer uses colors on tasks to indicate difference uses/purposes and would like a graphical representation of this. So I’ve set up two variants for them;

[cid:image005.jpg@01D3EDB8.A77AE1D0][cid:image006.jpg@01D3EDB8.A77AE1D0]


Another two points;

  1.  Why is color called Display Color, and not color as in the rest of the application?
  2.  When querying on colors it would also be easier if the color names could work

[cid:image007.jpg@01D3EDB8.A77AE1D0][cid:image008.jpg@01D3EDB8.A77AE1D0]


By the way – excellent work with this app. It is really useful in many contexts.

BR
Michael

Fra: krmorse <notifications@github.com>
Sendt: 16 May 2018 16:49
Til: RallyCommunity/CustomChart <CustomChart@noreply.github.com>
Cc: Michael Østerberg Jakobsen <michael.jakobsen@proimpactive.com>; Author <author@noreply.github.com>
Emne: Re: [RallyCommunity/CustomChart] Display Color Text values instead of Hex values (#39)


This is good feedback. I can't read hex either. Can you post a screenshot of your chart configuration so I can understand exactly what you're trying to visualize? Thanks!

**Comment by michael-jakobsen-dk** [comment]
Yes, that would make great sense.

The pictures are here:
![1](https://user-images.githubusercontent.com/17159651/40472462-dfc0bd74-5f39-11e8-9f90-d2c72733ab31.jpg)
![2](https://user-images.githubusercontent.com/17159651/40472464-e20b3f64-5f39-11e8-838e-ea2e6d2264da.jpg)
![3](https://user-images.githubusercontent.com/17159651/40472469-e5594f6c-5f39-11e8-8057-2ca36d010ebe.jpg)
![4](https://user-images.githubusercontent.com/17159651/40472474-e7339dec-5f39-11e8-82ec-48318888ff4f.jpg)

**Comment by larssolar** [comment]
Has this been implemented?

**Comment by krmorse** [comment]
@larssolar Unfortunately not quite yet.  I did a quick spike around this and also changing up the display colors so the pie slices would also correspond to the hex colors, but I haven't gotten it shipped yet.  Would love to revisit soon!

**Comment by larssolar** [comment]
Thank you for the response. I'm looking forward to this change as I really miss this feature. 
BR Lars

**Comment by krmorse** [comment]
@larssolar, @michael-jakobsen-dk, i think i got it done.  would you be interested in helping test it?
you can use this source in a custom html panel: https://github.com/RallyCommunity/CustomChart/blob/43e78bdf789ae6a3df8be7995d270e802d08ed96/deploy/App-uncompressed.html

i wrote automated tests and did manual testing for pie, bar and column (both aggregating by DisplayColor and stacking by it) and it all seemed to work for me, but i'd love some more 👀 if you have time!

**Comment by michael-jakobsen-dk** [comment]
Looks good from here.

Great job..

**Comment by krmorse** [comment]
Great!  I'll get this merged and promoted into the in-product community app catalog on rally1 shortly...
